server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /img/ {
        alias /usr/share/nginx/html/img/;
    }
    location /Recipes-pics/ {
        alias /usr/share/nginx/html/Recipes-pics/;
    }
    location /dist/ {
        alias /usr/share/nginx/html/dist/;
    }
}
